## Hydra Settings ##
defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
hydra:
  run:
    dir: .
  output_subdir: null

## Finetuning Settings ##
dataset:
  name: glue
  task_name: sst2
  text_column_name: sentence

tokenizer:
  name: bert-base-uncased

dataloader:
  hessian_batch_size: 800
  mini_hessian_batch_size: 1
  data_index: 0
  device_ids: null

model: "ckpt/princeton-nlp/unsup-simcse-bert-base-uncased/AdamW_lr1e-6/checkpoint-14040"

hessian:
  top_n: 15
  backprop_inputs: True

output_dir: "output/hessian/inputs/princeton-nlp-unsup-simcse-bert-base-uncased/AdamW/overfit/data_${dataloader.data_index}"
