## Hydra Settings ##
defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
hydra:
  run:
    dir: .
  output_subdir: null

## Finetuning Settings ##
dataset:
  name: glue
  task_name: sst2
  text_column_name: sentence

tokenizer:
  name: bert-base-uncased

dataloader:
  hessian_batch_size: 800
  mini_hessian_batch_size: 1
  data_index: 0

model: "ckpt/bert-base-uncased/AdamW_lr1e-6/checkpoint-4212"
use_safetensors: True

hessian:
  top_n: 15
  backprop_inputs: True

output_dir: "output/hessian/inputs/bert-base-uncased/AdamW/minloss/data_${dataloader.data_index}"
