## Hydra Settings ##
defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
hydra:
  run:
    dir: .
  output_subdir: null

## Finetuning Settings ##
dataset:
  name: glue
  task_name: sst2
  text_column_name: sentence

tokenizer:
  name: bert-base-uncased

dataloader:
  hessian_batch_size: 800
  mini_hessian_batch_size: 2
  device_ids: null

model: "ckpt/bert-base-uncased/SGD_lr1e-2/checkpoint-14040"
use_safetensors: True

hessian:
  top_n: 15
  backprop_inputs: False

output_dir: "output/hessian/params/bert-base-uncased/SGD/overfit"
